### ISSUE TITLE
Add Feature - Ignore URL patterns

### ISSUE THREAD

**Issue by tianlangwu** [hyunjiLeeTech/URL-FI#12]
Hi, I would like to add a feature to ignore URL pattern(s) using a text file.
For example, if you write 'https://www.google.com" in the text file (ignore-urls.txt), then run the command $ tool-name --ignore ignore-urls.txt index.html. Your tool will check all URLs in index.html, but ignore the URLs in ignore-url.txt which is "https://www.google.com" in this case.

Please let me know if I can work on this new feather, thanks!

**Comment by hyunjiLeeTech** [comment]
I've assigned this issue to you. Thanks.

**Comment by tianlangwu** [comment]
I found that your tool isn't working properly.
![image](https://user-images.githubusercontent.com/60892464/96199704-1fb40f00-0f26-11eb-9016-ad1d76377cc7.png)

It can't print link, and it stops going to the readFile function I don't why.
did I do anything wrong? Can you please check is it working on your computer?

**Comment by hyunjiLeeTech** [comment]
I've resolved it. Can you try it again?

**Comment by tianlangwu** [comment]
thanks, it works!

**Comment by hyunjiLeeTech** [comment]
Close this issue with e8ea523. Thanks!
