### ISSUE TITLE
ERROR: Error: getaddrinfo ENOTFOUND s-aleinikov.blog.ca

### ISSUE THREAD

**Issue by klee214** [hyunjiLeeTech/URL-FI#2]
In the test.html line 9 and line 10, it throws some error (which is of course idk lol). You need to handle the error... Also, your code is checking the same url twice because your regex is catching the same url twice both inside the <a href> and normal <p>. I wonder if it is what you intend.

**Comment by hyunjiLeeTech** [comment]
Can you please tell me what error it throws back on line 9 and 10?

About checking the url twice thing, it is because I check both http:// and https:// for one link. That is my intention.

**Comment by klee214** [comment]
So... when you run the code with test.html. it throws Error: getaddrinfo ENOTFOUND s-aleinikov.blog.ca. Perhaps the url doesn't exist. When it throws the error it automatically terminate the program if you not handle the error such as try catch...

**Comment by hyunjiLeeTech** [comment]
I've found ENOTFOUND means client was not able to connect to given address (https://stackoverflow.com/questions/23259697/error-getaddrinfo-enotfound-in-nodejs-for-get-call) so it gives the error. I've erased some urls creating ENOTFOUND error in test file. Close issue. Thanks.
